name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install medical-web-portal dependencies
        working-directory: apps/medical-web-portal
        run: npm ci

      - name: Install admin-dashboard dependencies
        working-directory: apps/admin-dashboard
        run: npm ci

      - name: Install API Gateway dependencies
        working-directory: services/api-gateway
        run: npm ci

      - name: Install appointment-service dependencies
        working-directory: services/appointment-service
        run: npm ci

      - name: Install auth-service dependencies
        working-directory: services/auth-service
        run: npm ci

      - name: Install billing-service dependencies
        working-directory: services/billing-service
        run: npm ci

      - name: Install doctor-service dependencies
        working-directory: services/doctor-service
        run: npm ci

      - name: Install notification-service dependencies
        working-directory: services/notification-service
        run: npm ci

      - name: Install patient-service dependencies
        working-directory: services/patient-service
        run: npm ci

      - name: Install pharmacy-service dependencies
        working-directory: services/pharmacy-service
        run: npm ci
